# Generated by Django 4.2.7 on 2023-11-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='colour',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Green', 'Green'), ('LightBlue', 'LightBlue'), ('Navy', 'Navy'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(choices=[(2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015')]),
        ),
    ]
