# Generated by Django 4.2.7 on 2023-11-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_booked',
            new_name='booking_date',
        ),
    ]
