# Generated by Django 4.2.7 on 2023-11-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_date_booked_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
