# Generated by Django 4.2.7 on 2023-11-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_car_pricing_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupe',
            fields=[
                ('car_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.car')),
                ('has_panoramic_roof', models.BooleanField(default=False)),
            ],
            bases=('main.car',),
        ),
        migrations.CreateModel(
            name='Sedan',
            fields=[
                ('car_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.car')),
                ('trunk_capacity', models.IntegerField()),
            ],
            bases=('main.car',),
        ),
    ]
