# Generated by Django 4.2.7 on 2023-11-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_car_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_cancelled',
        ),
    ]
