# Generated by Django 4.2.7 on 2023-11-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_booking'),
        ('main', '0009_remove_car_is_cancelled'),
    ]

    operations = [
    ]
